# Generated by Django 4.0.2 on 2022-02-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0002_photo_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
