# Generated by Django 4.0.2 on 2022-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0003_delete_photo_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='audios/', verbose_name='')),
            ],
        ),
    ]
