# Generated by Django 4.0.2 on 2022-02-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0004_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='videofile',
            new_name='audiofile',
        ),
    ]
