# Generated by Django 4.0.2 on 2022-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0005_rename_videofile_audio_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audiofile',
            field=models.FileField(blank=True, null=True, upload_to='audios/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.CharField(blank=True, help_text='You may type your story here', max_length=10000),
        ),
    ]
