# Generated by Django 4.0.2 on 2022-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0007_remove_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.CharField(blank=True, default='Hii', help_text='You may type your story here', max_length=10000),
        ),
    ]
