# Generated by Django 4.0.2 on 2022-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0008_alter_audio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.CharField(blank=True, default='', help_text='You may type your story here', max_length=10000),
        ),
    ]
